/* ==========================================================================
   VIRTUAL OFFICE PORTFOLIO
   ---------------------------------------------------------------------------
   Single-file build. Sections below mirror the requested architecture:

     data/      -> DATA           (edit this block only, to change content)
     scene/     -> Lighting, OfficeScene, CameraController
     components/-> makeDesk, makeChair, makeNPC, makeMeetingRoom, ...
     App        -> boot(), animate()
   ========================================================================== */

/* ==========================================================================
   1 · DATA  —  everything you'll ever want to edit lives here.
   Anything wrapped in {{ }} is a placeholder waiting for your real value.
   ========================================================================== */
const DATA = {

  owner: {
    name: "GeoffHaward Christy",
    role: "Frontend Developer",
    location: "Gandhinagar / Ahmedabad, Gujarat, India",
    years: "3 yrs 5 mos",
    summary:
      "I build the parts of enterprise software people actually touch all day — HR service portals, project management systems, dashboards and mobile apps. Mostly React and Angular on the front, Java Spring Boot REST APIs on the other side of the fence, which means I can debug a broken payload instead of just reporting it.",
    pitch: [
      "3 yrs 5 mos shipping production frontends across two product companies.",
      "Comfortable across React, Angular, React Native, Next.js and Shopify Liquid.",
      "Have built and consumed REST APIs in Java Spring Boot — not just integrated them.",
      "Role-based access control, dashboards and Chrome Extensions in live products."
    ],
    resumeUrl: "{{link-to-your-resume.pdf}}"
  },

  contact: {
    email: "geoffhawardchristy@gmail.com",
    phone: "+91 88496 43784",
    linkedin: "linkedin.com/in/geoffhaward-christy",
    github: "github.com/geoffhawardchristy-nam",
  },

  /* ---------- WORKSTATIONS -> projects. Order matches the desks on the floor. */
  "projects": [
      {
        "id": "ws01",
        "station": "Workstation 01",
        "name": "",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "",
        "tech": [
         
        ],
        "description": "",
        "responsibilities": [
          
        ],
        "features": [
          
        ],
        "apis": [
         
        ],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "ws02",
        "station": "Workstation 02",
        "name": "",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "",
        "tech": [
         
        ],
        "description": "",
        "responsibilities": [
          
        ],
        "features": [
         
        ],
        "apis": [
          
        ],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "ws03",
        "station": "Workstation 03",
        "name": "",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "",
        "tech": [
         
        ],
        "description": "",
        "responsibilities": [
        
        ],
        "features": [
          
        ],
        "apis": [
         
        ],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "ws04",
        "station": "Workstation 04",
        "name": "Project Management System (PMS)",
        "company": "Evision IT Solution Pvt. Ltd.",
        "role": "Frontend Developer",
        "duration": "2022 – 2024",
        "screen": "kanban",
        "tech": [
          "Angular",
          "TypeScript",
          "RxJS",
          "Reactive Forms",
          "Java Spring Boot",
          "RBAC"
        ],
        "description": "Projects, sprints, timesheets and approvals for delivery teams — the system the company ran its own work on.",
        "responsibilities": [
          "Built lazy-loaded feature modules for projects, tasks and timesheets",
          "Wrote complex Reactive Forms with cross-field validation",
          "Centralised HTTP error handling in interceptors",
          "Implemented role-based menus and route guards",
          "Contributed to Spring Boot REST endpoints where the frontend needed a better-shaped response"
        ],
        "features": [
          "Sprint board with drag-and-drop",
          "Timesheet entry with approval flow",
          "Project health summaries",
          "Audit history per record"
        ],
        "apis": [
          "Spring Boot REST",
          "Auth interceptor + guards",
          "Timesheet & approval services"
        ],
        "challenge": "The initial bundle carried the whole application, so first load was slow for users who only ever opened one module.",
        "solution": "Split features into lazy-loaded routes and moved shared UI into a single shared module, so each area downloads only when it is opened.",
        "impact": "Noticeably faster first paint, and adding a new module stopped making every other page slower."
      },
      {
        "id": "ws05",
        "station": "Workstation 05",
        "name": "Shopify Storefront Build",
        "company": "Evision IT Solution Pvt. Ltd.",
        "role": "Frontend Developer",
        "duration": "2022 – 2024",
        "screen": "shop",
        "tech": [
          "Shopify",
          "Liquid",
          "JavaScript",
          "HTML",
          "CSS"
        ],
        "description": "Custom Shopify theme work: sections merchants could rearrange themselves, without calling a developer for every banner change.",
        "responsibilities": [
          "Built custom Liquid sections and schema-driven settings",
          "Implemented product, collection and cart page customisations",
          "Optimised images and above-the-fold loading",
          "Fixed cross-browser and mobile layout issues"
        ],
        "features": [
          "Merchant-editable sections",
          "Custom cart drawer",
          "Collection filtering",
          "Mobile-first product pages"
        ],
        "apis": [
          "Shopify AJAX Cart API",
          "Storefront metafields"
        ],
        "challenge": "Content changes kept coming back as developer tickets.",
        "solution": "Exposed the right settings through section schema so copy, ordering and imagery became merchant-editable in the theme editor.",
        "impact": "The client stopped needing a developer for routine content updates."
      },
      {
        "id": "ws06",
        "station": "Workstation 06",
        "name": "",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [
          
        ],
        "description": "",
        "responsibilities": [
          
        ],
        "features": [
          
        ],
        "apis": [
         
        ],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-3",
        "station": "Evision floor · desk 03",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-4",
        "station": "Evision floor · desk 04",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-5",
        "station": "Evision floor · desk 05",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-6",
        "station": "Evision floor · desk 06",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-7",
        "station": "Evision floor · desk 07",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d1-8",
        "station": "Evision floor · desk 08",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-1",
        "station": "Evision floor · desk 09",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-2",
        "station": "Evision floor · desk 10",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-3",
        "station": "Evision floor · desk 11",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-4",
        "station": "Evision floor · desk 12",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-5",
        "station": "Evision floor · desk 13",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-6",
        "station": "Evision floor · desk 14",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-7",
        "station": "Evision floor · desk 15",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d2-8",
        "station": "Evision floor · desk 16",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-1",
        "station": "Evision floor · desk 17",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-2",
        "station": "Evision floor · desk 18",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-3",
        "station": "Evision floor · desk 19",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-4",
        "station": "Evision floor · desk 20",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-5",
        "station": "Evision floor · desk 21",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-6",
        "station": "Evision floor · desk 22",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-7",
        "station": "Evision floor · desk 23",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d3-8",
        "station": "Evision floor · desk 24",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-1",
        "station": "Evision floor · desk 25",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-2",
        "station": "Evision floor · desk 26",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-3",
        "station": "Evision floor · desk 27",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-4",
        "station": "Evision floor · desk 28",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-5",
        "station": "Evision floor · desk 29",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-6",
        "station": "Evision floor · desk 30",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-7",
        "station": "Evision floor · desk 31",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d4-8",
        "station": "Evision floor · desk 32",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-1",
        "station": "Evision floor · desk 33",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-2",
        "station": "Evision floor · desk 34",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-3",
        "station": "Evision floor · desk 35",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-4",
        "station": "Evision floor · desk 36",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-5",
        "station": "Evision floor · desk 37",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-6",
        "station": "Evision floor · desk 38",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-7",
        "station": "Evision floor · desk 39",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d5-8",
        "station": "Evision floor · desk 40",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d6-1",
        "station": "Evision floor · desk 41",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d6-2",
        "station": "Evision floor · desk 42",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision-d6-3",
        "station": "Evision floor · desk 43",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d1-1",
        "station": "Evision 207 · desk 01",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d1-2",
        "station": "Evision 207 · desk 02",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d1-3",
        "station": "Evision 207 · desk 03",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d1-4",
        "station": "Evision 207 · desk 04",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-1",
        "station": "Evision 207 · desk 05",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-2",
        "station": "Evision 207 · desk 06",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-3",
        "station": "Evision 207 · desk 07",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-4",
        "station": "Evision 207 · desk 08",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-5",
        "station": "Evision 207 · desk 09",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d2-6",
        "station": "Evision 207 · desk 10",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-1",
        "station": "Evision 207 · desk 11",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-2",
        "station": "Evision 207 · desk 12",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-3",
        "station": "Evision 207 · desk 13",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-4",
        "station": "Evision 207 · desk 14",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-5",
        "station": "Evision 207 · desk 15",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d3-6",
        "station": "Evision 207 · desk 16",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-1",
        "station": "Evision 207 · desk 17",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-2",
        "station": "Evision 207 · desk 18",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-3",
        "station": "Evision 207 · desk 19",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-4",
        "station": "Evision 207 · desk 20",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-5",
        "station": "Evision 207 · desk 21",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d4-6",
        "station": "Evision 207 · desk 22",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-1",
        "station": "Evision 207 · desk 23",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-2",
        "station": "Evision 207 · desk 24",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-3",
        "station": "Evision 207 · desk 25",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-4",
        "station": "Evision 207 · desk 26",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-5",
        "station": "Evision 207 · desk 27",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "evision2-d5-6",
        "station": "Evision 207 · desk 28",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d1-3",
        "station": "Logieagle floor · desk 03",
        "name": "Gym Management & Workout Tracking Platform",
        "company": "",
        "role": "Frontend Developer - Functionality, RBAC & Optimization",
        "duration": "",
        "screen": "code",
        "tech": [
          "React.js",
          "JavaScript (ES6+)",
          "CSS3",
          "React Hooks",
          "Role-Based Access Control (RBAC)",
          "Responsive Design",
          "Git"
        ],
        "description": "Built the frontend of a gym management platform in React, where the same application served different types of users - gym admins managing members and plans, trainers assigning and monitoring workouts, and members logging their own sessions. Most of the work was on the functionality side: role-based access across the app, and the workout structure itself with exercises, sets, reps, weights and timers. Alongside building features, I optimised the code as the app grew and the workout screens became heavier.",
        "responsibilities": [
          "Implemented role-based access so admins, trainers and members each got their own views, permissions and actions",
          "Built role-driven navigation and route guarding so users could only reach screens allowed for their role",
          "Built member and trainer management screens for the admin side",
          "Built workout plan creation and assignment grouping exercises into routines and days",
          "Built workout logging with sets, reps, weight and duration recorded per set",
          "Implemented rest timers between sets with start, pause and skip controls",
          "Built progress tracking so previous session values were visible while logging",
          "Built the exercise library with search, category filters and detail views",
          "Optimised rendering on workout screens where many inputs updated frequently",
          "Refactored repeated logic into reusable components and custom hooks",
          "Built responsive layouts so the platform worked on desktop and mobile"
        ],
        "features": [
          "Role-based access with separate Admin, Trainer and Member experiences",
          "Navigation and available actions rendered from the logged-in user's role",
          "Admin side - member and trainer management with plan assignment",
          "Trainer side - building workout plans and assigning them to members",
          "Member side - logging workouts set by set with reps, weight and duration",
          "Rest timer between sets with pause and skip",
          "Previous session values shown while logging, for reference",
          "Progress history per exercise across sessions",
          "Exercise library with search, categories and detail view",
          "Responsive layouts working on desktop and mobile"
        ],
        "apis": [],
        "challenge": "The same screens had to behave differently for three roles a workout plan is something an admin oversees, a trainer builds and assigns, and a member simply follows, so permission logic could not just hide a button here and there. Done carelessly, role checks get scattered across every component and become impossible to trust. The workout data added its own difficulty: a plan holds days, a day holds exercises, an exercise holds sets, and each set has its own reps, weight and completion state, so editing one value meant updating something several levels deep without disturbing anything above it. The logging screen also carried a large number of inputs at once, and every keystroke risked re-rendering the whole workout, which made it feel sluggish with rest timers updating every second on top of that.",
        "solution": "Role and permission data was held in one place after login, and navigation, routes and actions were rendered from it rather than being checked ad hoc inside components so an unauthorised screen was never reachable, and every action re-checked permission before firing. Shared screens were built once with role-driven variations instead of duplicating a version per role, which kept the three experiences consistent as features were added. The workout state was kept in a normalised structure with identifiers rather than deeply nested objects, so changing one set touched only that set. Each exercise and set became its own memoised component so a value change re-rendered just that input, and the rest timer was isolated with its own state so its per-second updates never propagated outward. Repeated patterns were pulled into reusable components and custom hooks, which cut duplication across all three role views.",
        "impact": "One application served admins, trainers and members from a single codebase, with each role seeing only what they were entitled to instead of needing separate builds or separate portals. Members could log a full workout set by set without the interface lagging, even on long routines, and the shared components and hooks meant new features landed across all three role views at once rather than being built three times."
      },
      {
        "id": "logieagle-d1-4",
        "station": "Logieagle floor · desk 04",
        "name": "Backend - Java Spring Boot REST APIs",
        "company": "",
        "role": "Backend Developer - REST API Development",
        "duration": "",
        "screen": "code",
        "tech": [
          "Java",
          "Spring Boot",
          "Spring Data JPA",
          "Hibernate",
          "REST APIs",
          "MySQL / PostgreSQL",
          "Maven",
          "Postman",
          "Git"
        ],
        "description": "Built the backend REST APIs for a client project using Java Spring Boot. The requirement was a straightforward set of CRUD endpoints, so I handled it end to end designing the entities, writing the controller, service and repository layers, connecting the database, and testing every endpoint in Postman before handover.",
        "responsibilities": [
          "Designed entity models and their database mappings using Spring Data JPA",
          "Built CRUD REST endpoints following a controller, service and repository structure",
          "Implemented request validation and appropriate HTTP status codes for each operation",
          "Handled exceptions centrally so error responses stayed consistent across endpoints",
          "Configured the database connection and managed schema through JPA entities",
          "Tested every endpoint in Postman with real payloads before handover",
          "Documented the endpoints and response structures for the frontend side"
        ],
        "features": [
          "Full CRUD REST endpoints - create, read, update and delete",
          "Layered structure separating controller, service and repository responsibilities",
          "Request validation with clear error messages on invalid input",
          "Consistent JSON response format across all endpoints",
          "Centralised exception handling with proper HTTP status codes",
          "Database persistence through Spring Data JPA and Hibernate",
          "Postman collection maintained for endpoint testing"
        ],
        "apis": [
          "CRUD endpoints — GET, POST, PUT, DELETE for the client's core modules"
        ],
        "challenge": "The scope was small, but small backends are exactly where shortcuts get taken logic ends up inside controllers, error responses come back in a different shape from every endpoint, and the frontend then has to handle each case separately. Since I was building the APIs that would be consumed on the frontend side, the response and error structure had to be predictable from the start rather than something to clean up later.",
        "solution": "Kept the layers properly separated controllers only handled requests and responses, business logic stayed in the service layer, and database access stayed in repositories. Validation ran at the request level so invalid input never reached the service, and exception handling was centralised so every endpoint returned errors in the same shape with the correct status code. Each endpoint was verified in Postman with real payloads before being handed over, so the contract was confirmed rather than assumed.",
        "impact": "Delivered a working set of REST APIs for the client, with a consistent response and error structure that the frontend could integrate against without guesswork. Having built the API side myself also made it easier to discuss response structures with backend developers on other projects, since I understood what was being asked for from their end."
      },
      {
        "id": "logieagle-d1-5",
        "station": "Logieagle floor · desk 05",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d1-6",
        "station": "Logieagle floor · desk 06",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d1-7",
        "station": "Logieagle floor · desk 07",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d1-8",
        "station": "Logieagle floor · desk 08",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d2-3",
        "station": "Logieagle floor · desk 11",
        "name": "Chrome Extension - Screen & Video Recorder",
        "company": "",
        "role": "Frontend Developer - Chrome Extension",
        "duration": "",
        "screen": "code",
        "tech": [
          "Vanilla JavaScript (ES6+)",
          "HTML5 / CSS3",
          "Canvas API",
          "Web Audio API",
          "Chrome Extension APIs (Manifest V3)",
          "MediaRecorder API",
          "Screen Capture API (getDisplayMedia)",
          "getUserMedia (camera & microphone)",
          "chrome.storage",
          "Service Worker",
          "Content Scripts",
          "REST APIs",
          "Git"
        ],
        "description": "Built a Chrome Extension for a German client that let users record their screen, browser tab or camera directly from the browser, with role-based access control deciding what each user could record, view and share. The entire extension was written in plain JavaScript and CSS on top of manifest.json no framework and no build step.",
        "responsibilities": [
          "Built a canvas-based compositing layer that merged screen, facecam and logo into a single video track",
          "Implemented watermark and client logo overlay with configurable position, size and opacity",
          "Built the export flow preview, format selection and local download of the final recording"
        ],
        "features": [
          "Screen, tab and camera recording with microphone audio",
          "Facecam picture-in-picture overlay on top of the screen share, with draggable position",
          "Watermark and company logo overlay burned into the recorded video",
          "Configurable overlay position, size and opacity per user",
          "Pause, resume and stop controls with a live recording timer",
          "Role-based access with separate Admin, Manager and Viewer permissions",
          "Local preview and export/download of the final recording",
          "Recording history with upload status",
          "Auto-upload to the backend with retry on failure",
          "Configurable video quality and mic/camera toggles",
          "Recording continues even after the popup is closed"
        ],
        "apis": [
          "navigator.mediaDevices.getDisplayMedia (screen & tab capture)",
          "navigator.mediaDevices.getUserMedia (camera & microphone)",
          "Canvas API - captureStream and drawImage compositing",
          "Web Audio API - mixing mic and system audio tracks",
          "MediaRecorder API",
          "chrome.storage (local & sync)",
          "chrome.runtime messaging",
          "REST APIs for authentication, role lookup and video upload"
        ],
        "challenge": "The screen share, the facecam and the logo were three independent sources, but the export had to be one single video file with everything baked in. MediaRecorder can only record one stream, and Manifest V3's service worker has no DOM, so there was nowhere obvious to run a canvas. On top of that, drawing every frame while also encoding video pushed CPU usage up on long recordings, the facecam overlay had to stay sharp without distorting its aspect ratio at any screen resolution, and audio from the microphone and the shared tab arrived as separate tracks.",
        "solution": "Composited everything on a canvas - the screen frame was drawn first, then the facecam in its corner box, then the logo watermark, redrawn on every animation frame. That canvas was turned back into a video track with captureStream, and the microphone and system audio were merged into one track using the Web Audio API, so MediaRecorder received a single ready-made stream. The canvas ran outside the popup so recording survived the popup closing, the draw loop was throttled to the target frame rate instead of running unbounded, and overlay dimensions were calculated from the source resolution so the facecam kept its aspect ratio on any screen. MediaRecorder emitted timed chunks rather than one blob, which kept memory flat and let export and upload start without waiting for the full recording.",
        "impact": "Users could produce branded, presenter-style videos in one pass screen, face and company logo already merged instead of recording raw footage and editing it afterwards in a separate tool. The client's branding appeared on every recording automatically, admins controlled who could record and share, and the whole thing ran on plain JavaScript with no build pipeline or external recording service."
      },
      {
        "id": "logieagle-d2-4",
        "station": "Logieagle floor · desk 12",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d2-5",
        "station": "Logieagle floor · desk 13",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d2-6",
        "station": "Logieagle floor · desk 14",
        "name": "Maloo Group - Mobile App (iOS & Android)",
        "company": "",
        "role": "Frontend Developer -  End-to-End Mobile App Ownership",
        "duration": "",
        "screen": "code",
        "tech": [
          "React Native",
          "Expo",
          "JavaScript / TypeScript",
          "Redux Toolkit",
          "React Navigation",
          "Axios / Fetch API",
          "REST APIs",
          "JWT Authentication",
          "AsyncStorage",
          "Postman",
          "Git",
          "Firebase",
          "Notifee"
        ],
        "description": "Built the Maloo Group mobile application for both iOS and Android using React Native with Expo. This was full implementation ownership rather than one slice of the work building every screen, managing state with Redux Toolkit, integrating every API with the backend, implementing role-based access across the app, and verifying it on real devices for both platforms.",
        "responsibilities": [
          "Built the complete mobile application for iOS and Android from a single React Native codebase",
          "Set up and configured the Expo project, navigation structure and app-level architecture",
          "Built every screen from the designs, handling platform differences between iOS and Android",
          "Managed global application state using Redux Toolkit slices, async thunks and selectors",
          "Integrated all REST APIs with the backend, verifying each endpoint in Postman before wiring it in",
          "Implemented JWT authentication with token storage, expiry handling and protected navigation",
          "Implemented RBAC so screens, navigation and actions were gated by the logged-in user's role",
          "Handled loading, empty and error states across every API-driven screen",
          "Implemented device permissions - notifications for both platforms",
          "Generated development and test builds for QA verification on real devices",
          "Fixed device-specific and OS-version-specific issues reported during testing"
        ],
        "features": [
          "Single codebase running on both iOS and Android",
          "Role-based access control - navigation, screens and actions change per user role",
          "Token-based authentication with persisted session and auto logout on expiry",
          "Centralised API layer with auth headers and error handling in one place",
          "Redux Toolkit state management with async thunks for all API-driven data",
          "Error and empty states handled gracefully across screens",
          "Native device features - camera, storage and push notifications",
          "Responsive layouts adapting across phone sizes and both platforms"
        ],
        "apis": [
          "Authentication and JWT token endpoints",
          "Role and permission endpoints driving RBAC",
          "Core module CRUD endpoints consumed across app screens",
          "File and image upload endpoints (multipart/form-data)",
          "Push notification registration endpoints"
        ],
        "challenge": "One codebase had to behave correctly on two platforms that differ in real ways navigation gestures, keyboard behaviour, safe areas, permission prompts and status bar handling all needed platform-specific attention, and bugs frequently appeared only on one OS or on specific device sizes. RBAC added another layer, because role rules had to control not just what a screen showed but which routes even existed for that user, and getting that wrong meant a user could reach a screen they had no permission for. Managing state across authentication, roles and API data through Redux Toolkit meant those concerns had to stay cleanly separated or the store would become impossible to reason about.",
        "solution": "Kept one shared codebase with platform-specific handling isolated where it was genuinely needed instead of forking screens, and tested on real iOS and Android devices rather than trusting simulators. RBAC was driven by the role and permission set returned at login and held in the Redux store, with navigation built conditionally from that so an unauthorised screen was never registered as a route at all, and every action re-checked permission before firing. The Redux store was split into focused slices for auth, roles and each data module, with async thunks handling API calls so components stayed free of fetch logic. All API calls went through one wrapper handling token attachment and error catching, and every endpoint was verified in Postman before integration. On the release side, builds went to testers first and only reached the stores once verified, which kept store submissions from turning into rework.",
        "impact": "Delivered the full implementation of a production mobile application running on both iOS and Android from a single codebase screens, state management, API integration and role-based access all owned end to end. Each user type saw only the parts of the app they were entitled to, and because the API, auth and permission layers were centralised, new screens and modules could be added without rebuilding that groundwork each time."
      },
      {
        "id": "logieagle-d2-7",
        "station": "Logieagle floor · desk 15",
        "name": "Spotlight Analytics Dashboard - Frontend & UI",
        "company": "",
        "role": "Frontend Developer - UI Design & Functionality",
        "duration": "",
        "screen": "code",
        "tech": [
          "Angular",
          "React",
          "JavaScript (ES6+)",
          "TypeScript",
          "HTML5 / CSS3",
          "Figma / Adobe XD (design handoff)",
          "Responsive Design",
          "Git"
        ],
        "description": "Worked on Spotlight, an analytics dashboard, owning the frontend end to end. The product was originally built in Angular and later migrated to React I built the screens in both, so every dashboard screen and the entire Google and Meta ads campaign creation flow was implemented twice, once in each framework. New screens were built from scratch off Figma and Adobe XD handoffs, existing screens were rebuilt as part of the redesign, and I handled all the client-side functionality along with optimising the code as the dashboard grew.",
        "responsibilities": [
          "Built new dashboard screens from scratch off Figma and Adobe XD designs, pixel-perfect across breakpoints",
          "Implemented the dashboard redesign, rebuilding existing screens on a consistent spacing, colour and typography system in code",
          "Rebuilt the dashboard and campaign flow in React after the product moved off Angular",
          "Mapped Angular patterns — services, two-way binding, template logic — onto React equivalents without changing behaviour",
          "Built the complete Google Ads and Meta Ads campaign creation flow as a multi-step form UI",
          "Implemented conditional field logic so the form adapted based on platform, objective and campaign type",
          "Built all client-side functionality and interactions in JavaScript",
          "Implemented form validation with inline error handling across every campaign step",
          "Optimised existing code — removed duplication, refactored repeated logic into reusable components",
          "Improved dashboard rendering performance on data-heavy screens",
          "Built responsive layouts across desktop, tablet and mobile"
        ],
        "features": [
          "Multi-step campaign creation flow for Google Ads and Meta Ads",
          "Platform-specific form fields that change based on campaign objective and type",
          "Step-by-step progress with validation before moving forward",
          "Draft state so an in-progress campaign is not lost between steps",
          "Redesigned dashboard screens with a consistent visual system",
          "Reusable UI components shared across dashboard screens",
          "Responsive layouts working from desktop down to mobile"
        ],
        "apis": [],
        "challenge": "Google Ads and Meta Ads campaigns do not share the same structure each platform has its own set of fields, objectives and rules, and within a platform the fields change depending on the campaign type the user picks. Building that as a single form meant a large amount of conditional rendering, and done carelessly it would have turned into deeply nested conditions that nobody could extend later. The dashboard itself had also grown over time with duplicated logic and inconsistent screens, so new work had to be built while cleaning up what was already there.",
        "solution": "Built the campaign flow as a configuration-driven form instead of hardcoding each variation - field definitions, visibility rules and validation were described in one place, and the UI rendered from that, so adding a platform or campaign type meant editing config rather than rewriting components. Each step was kept as an isolated component with its own validation, which stopped the conditional logic from spreading across the flow. Alongside that, repeated patterns across the dashboard were pulled into shared components and the redesigned screens were rebuilt on a common spacing, colour and typography system, which cut duplication and made the older and newer screens look like one product.",
        "impact": "Users could create Google and Meta ad campaigns through a single guided flow instead of dealing with two separate platform interfaces, with validation catching mistakes before submission. The redesigned screens brought the dashboard onto one consistent visual system, and the refactoring work made new screens noticeably faster to build since the shared components were already in place."
      },
      {
        "id": "logieagle-d2-8",
        "station": "Logieagle floor · desk 16",
        "name": "Spotlight - API Integration",
        "company": "",
        "role": "Frontend Developer - API Integration",
        "duration": "",
        "screen": "code",
        "tech": [
          "Angular",
          "React",
          "JavaScript / TypeScript",
          "Axios / Fetch API",
          "REST APIs",
          "JSON",
          "Postman",
          "JWT Authentication",
          "Chrome DevTools",
          "Git"
        ],
        "description": "Handled the frontend side of every API integration on Spotlight. Before writing code I sat with the backend developer to agree what each endpoint would return, tested it in Postman with real payloads, and only then wired it into the dashboard screens and the ads campaign flow. Since the product was built in Angular and later migrated to React, the same integrations had to be rebuilt in both.",
        "responsibilities": [
          "Discussed API requirements with the backend developer before development - endpoints, payloads, response structure and field names",
          "Tested every endpoint in Postman with real payloads before integrating it into the UI",
          "Verified response shapes, status codes and error formats against what each screen actually needed",
          "Requested missing or restructured fields when a response did not fit the UI requirement",
          "Integrated dashboard analytics APIs into data-heavy screens with charts and tables",
          "Wired the Google and Meta ads campaign flow to its submit and validation endpoints",
          "Implemented JWT token handling - attaching tokens, expiry handling and redirects",
          "Handled loading, empty, success and error states on every API-driven screen",
          "Implemented server-side pagination, search and filter parameters on list screens",
          "Debugged CORS, status code and payload mismatch issues alongside the backend developer",
          "Rebuilt the same integrations in React after the product moved off Angular"
        ],
        "features": [
          "Centralised API layer handling base URL, auth headers and error catching in one place",
          "Token-based authentication with expiry handling and automatic logout",
          "Consistent loading, empty and error states across every data-driven screen",
          "Analytics endpoints feeding dashboard charts, tables and date-range filters",
          "Campaign flow wired to its submit and validation endpoints step by step",
          "Server-side pagination, search and filtering on list screens",
          "Response mapping layer keeping API structure separate from component logic",
          "Postman used per module to verify endpoints before and after integration"
        ],
        "apis": [
          "Analytics and reporting endpoints powering the dashboard",
          "Google Ads and Meta Ads campaign submission endpoints",
          "Authentication and JWT token endpoints",
          "User and account management CRUD endpoints"
        ],
        "challenge": "Frontend and backend were built in parallel, so screens were often ready before their endpoints were, and response structures kept shifting during development - a field renamed, nested differently, or returning null where the UI expected a value, each one silently breaking a screen. The analytics screens made this worse, since chart and table components needed data in a very specific shape while responses were structured around how the data was stored. Error formats also varied between endpoints, so the UI could not rely on one shape when deciding what to show. And because the product moved from Angular to React, every integration had to be rebuilt without any behaviour drifting from the original.",
        "solution": "Every integration started with a contract agreed with the backend developer endpoint, payload, exact field names and error format confirmed in Postman before the UI was touched. Where a response did not fit the screen, I raised it early and asked for the structure to change instead of patching it inside a component. All calls went through one central wrapper that attached the token, applied the base URL and caught failures in a single place, and responses passed through a mapping layer before reaching components, so chart and table data was reshaped in one file rather than in every screen. That separation is also what made the Angular to React migration manageable the API and mapping layers carried over cleanly, so the rebuild was mostly UI work rather than re-integration.",
        "impact": "Integration problems surfaced during the contract discussion and Postman testing rather than after screens were built, which cut back-and-forth with the backend developer sharply. Keeping auth, error handling and response mapping in one place meant backend changes were absorbed in a single file instead of across every screen, and it made the React rebuild significantly faster since the integration layer did not have to be written again from scratch."
      },
      {
        "id": "logieagle-d3-1",
        "station": "Logieagle floor · desk 17",
        "name": "iOS Build & Release Station",
        "company": "",
        "role": "Frontend Developer (React Native) - iOS Build & Release",
        "duration": "",
        "screen": "code",
        "tech": [
          "React Native",
          "Xcode",
          "CocoaPods",
          "App Store Connect",
          "TestFlight",
          "Apple Developer Portal",
          "Code Signing & Provisioning Profiles",
          "Git"
        ],
        "description": "Owned the complete iOS release cycle for our React Native app from generating signed builds in Xcode to publishing them live on the App Store. Every build that reached QA, clients or production users was archived, signed and uploaded from this desk, first through TestFlight for beta testing and then submitted to Apple for App Review.",
        "responsibilities": [
          "Configured certificates, App IDs and provisioning profiles in the Apple Developer portal",
          "Managed signing, capabilities and entitlements inside Xcode for every scheme",
          "Bumped version and build numbers before each release cycle",
          "Archived and uploaded signed builds to App Store Connect",
          "Managed TestFlight internal and external testing groups with release notes",
          "Collected tester feedback and crash logs, then shipped fix builds",
          "Prepared store listing assets screenshots, description, keywords, privacy details",
          "Submitted builds for App Review and resolved rejection feedback till approval",
          "Monitored crash reports and release health after go-live"
        ],
        "features": [
          "End-to-end iOS pipeline: Xcode archive to App Store Connect to TestFlight to production",
          "Separate Dev / Staging / Production schemes with different bundle IDs and API endpoints",
          "TestFlight internal group for the QA team and external group for client UAT",
          "Push notification setup using an APNs authentication key",
          "Phased release rollout for production updates"
        ],
        "apis": [
          "App Store Connect API",
          "Apple Push Notification service (APNs)",
          "REST APIs consumed by the mobile app"
        ],
        "challenge": "Code signing was the biggest blocker builds that compiled fine locally would fail at archive or upload with profile mismatch errors, expired certificates or unregistered device UDIDs. Every failed upload or App Review rejection cost close to a full day, because processing time plus a fresh review cycle pushed releases past the planned date.",
        "solution": "Standardised the release process with a pre-archive checklist covering version bump, certificate validity, capability checks and export compliance. Switched push notifications to an APNs authentication key instead of expiring certificates, kept distribution certificates and profiles centrally managed, and made a TestFlight internal build a mandatory gate before anything went to external testers or review. Store metadata, screenshots and demo credentials were kept ready in advance so review submissions never got blocked on missing information.",
        "impact": "Release cycle went from multiple days of trial-and-error to a predictable same-day process. Builds reached testers within roughly 30 minutes of code freeze, App Review rejections dropped to near zero, and the team could ship iOS hotfixes without waiting on anyone else."
      },
      {
        "id": "logieagle-d3-2",
        "station": "Logieagle floor · desk 18",
        "name": "QA Collaboration & Bug Fixing Desk",
        "company": "",
        "role": "Frontend Developer - Mobile Bug Fixing & QA Support",
        "duration": "",
        "screen": "code",
        "tech": [
          "React Native",
          "JavaScript / TypeScript",
          "Xcode",
          "Android Studio",
          "React Native Debugger",
          "Chrome DevTools",
          "Jira",
          "TestFlight",
          "Git"
        ],
        "description": "Worked directly with the QA team on the mobile application sitting with testers to reproduce reported issues on real devices, understanding what was actually expected versus what the app did, and fixing them in the same cycle. Most bugs were device or OS specific, so this desk was about reproducing, debugging and verifying on actual phones rather than just reading a ticket and pushing a patch.",
        "responsibilities": [
          "Reviewed bugs raised by QA and discussed each one with the tester before starting the fix",
          "Reproduced reported issues on real iOS and Android devices instead of relying only on simulators",
          "Identified whether an issue was a frontend defect, a backend response problem or a device-specific behaviour",
          "Debugged crashes and UI issues using Xcode logs, Android Studio Logcat and React Native Debugger",
          "Fixed layout, gesture, keyboard and navigation issues across different screen sizes and OS versions",
          "Clarified expected behaviour with QA and the product owner when a ticket was ambiguous",
          "Pushed fix builds to TestFlight and internal Android builds for retesting",
          "Verified fixes with QA and closed tickets only after their confirmation",
          "Tracked bug status, priority and regression notes in Jira"
        ],
        "features": [
          "Bug triage flow reproduce, classify, prioritise, fix, retest, close",
          "Device-wise testing across multiple iOS and Android phones and OS versions",
          "Frontend versus backend isolation before assigning a fix",
          "Regression checks on related screens after every fix",
          "Fix builds shipped to QA through TestFlight and internal Android distribution",
          "Ticket-level tracking with reproduction steps and root cause notes in Jira"
        ],
        "apis": [
          "REST APIs inspected requests and responses while isolating frontend versus backend defects",
          "Native device APIs - push notifications"
        ],
        "challenge": "A large share of QA-reported bugs could not be reproduced on the development machine they only appeared on specific devices, screen sizes or OS versions, and simulators behaved differently from real hardware. Tickets often described the symptom without the exact steps or device details, so time went into figuring out what actually happened rather than fixing it. Some issues also looked like frontend defects but were caused by backend responses or missing permissions, which meant fixes could get assigned to the wrong side and bounce back after retesting.",
        "solution": "Started sitting with QA directly instead of working only off the ticket text, walking through the exact steps on their device while they reproduced the issue. Reproduction details device model, OS version, build number and steps were agreed as mandatory on every ticket, which cut the back-and-forth sharply. Every reported issue was first isolated by checking the actual API request and response and the device logs, so frontend and backend defects were separated before any code was touched. Fix builds went out to QA through TestFlight and internal Android builds with clear notes on what changed and which screens needed a regression check, so verification stayed fast and fixes did not reopen.",
        "impact": "Bugs moved from reported to verified within the same cycle instead of bouncing between QA and development, and misassigned tickets dropped once frontend and backend issues were separated up front. Working directly with testers meant device-specific problems were caught and confirmed on real hardware before release, so fewer issues reached production users."
      },
      {
        "id": "logieagle-d3-3",
        "station": "Logieagle floor · desk 19",
        "name": "Serverless Web App - Frontend",
        "company": "",
        "role": "Frontend Developer - UI & Client-side Functionality",
        "duration": "",
        "screen": "code",
        "tech": [
          "JavaScript (ES6+)",
          "jQuery",
          "HTML5",
          "CSS3",
          "Responsive Design",
          "Git"
        ],
        "description": "Built the complete user interface for a web application hosted on AWS serverless infrastructure. The backend and API layer were handled by another developer my scope was the entire client side: converting designs into responsive HTML and CSS, and writing all the interactive functionality in JavaScript and jQuery without any framework or build step.",
        "responsibilities": [
          "Converted UI designs into responsive HTML and CSS layouts",
          "Built all client-side functionality and interactions in JavaScript and jQuery",
          "Implemented dynamic DOM rendering, show/hide logic and screen state handling",
          "Built reusable UI components modals, tabs, tables, dropdowns and accordions",
          "Implemented client-side form validation with inline error messages",
          "Handled responsive behaviour across desktop, tablet and mobile breakpoints",
          "Fixed cross-browser layout and behaviour inconsistencies",
          "Coordinated with the backend developer so the UI matched the data structure being rendered"
        ],
        "features": [
          "Fully responsive layouts across desktop, tablet and mobile",
          "Reusable jQuery components reused across multiple screens",
          "Client-side form validation with inline error messaging",
          "Interactive UI elements modals, tabs, filters and accordions",
          "Cross-browser compatible markup and styling"
        ],
        "apis": [],
        "challenge": "The entire interface ran on plain JavaScript and jQuery with no framework, so there was no component model, no reactive state and no build step. Every screen update had to be handled through manual DOM manipulation, and as the number of screens grew, the same UI patterns risked being rewritten again and again in slightly different ways. Layouts also had to hold up across different browsers and screen sizes without any CSS framework doing that work.",
        "solution": "Split the code into separate files per screen with a shared set of helper functions, so modals, tables, validation and toggle behaviour were written once and reused everywhere instead of being copied. CSS was organised with a consistent class structure and breakpoints defined in one place, which kept responsive behaviour predictable across screens. Browser-specific issues were tested and fixed as screens were built rather than left to the end.",
        "impact": "Delivered the full user interface of the product as the only frontend developer on it, with every screen responsive and working across browsers. Because the UI was built as plain static HTML, CSS and JavaScript, it deployed straight onto the project's serverless hosting with nothing extra to maintain on the frontend side."
      },
      {
        "id": "logieagle-d3-4",
        "station": "Logieagle floor · desk 20",
        "name": "Chatbot UI - Responsive Design",
        "company": "",
        "role": "Frontend Developer - UI Design & Implementation",
        "duration": "",
        "screen": "code",
        "tech": [
          "Tailwind CSS",
          "HTML5",
          "Responsive Design",
          "Git"
        ],
        "description": "Designed and built the complete chat interface for a chatbot using Tailwind CSS. My scope was purely the UI the full chat layout, message bubbles, input area and responsive behaviour across screen sizes. The conversation logic and integration were handled separately.",
        "responsibilities": [
          "Built the entire chatbot interface from scratch using Tailwind CSS utility classes",
          "Designed the chat layout message list, bubble styles, timestamps and input area",
          "Implemented distinct styling for user messages and bot responses",
          "Made the interface fully responsive across desktop, tablet and mobile",
          "Handled scroll behaviour so the latest message stays in view",
          "Built supporting UI states typing indicator, empty state and disabled input",
          "Kept spacing, colours and typography consistent using Tailwind's design tokens"
        ],
        "features": [
          "Clean chat interface with separate user and bot message styling",
          "Fully responsive layout that adapts from desktop to mobile",
          "Auto-scrolling message area anchored to the latest message",
          "Typing indicator and empty conversation state",
          "Fixed input bar with send action, comfortable on mobile",
          "Consistent spacing and colour system through Tailwind utilities"
        ],
        "apis": [],
        "challenge": "A chat interface behaves differently from a normal page the message area has to scroll on its own while the header and input bar stay fixed, and it must hold up when messages range from a single word to long paragraphs. On mobile this gets harder, because the on-screen keyboard shrinks the visible area and can push the input bar out of view. All of this had to be built with Tailwind utility classes alone, without writing custom CSS.",
        "solution": "Built the layout as a fixed-height flex column with the message list as the only scrollable region, so the header and input bar stayed anchored while the conversation scrolled. Message bubbles were given max-width constraints with proper word wrapping so both short replies and long paragraphs rendered cleanly. Responsive behaviour was handled entirely through Tailwind breakpoint prefixes, and repeated bubble and layout patterns were kept consistent so the same utility combinations were reused instead of being re-invented per screen.",
        "impact": "Delivered a ready-to-use chat interface that could be dropped straight into the product, working consistently from desktop down to mobile. Building it purely with Tailwind utilities meant no custom stylesheet to maintain and no CSS conflicts with the rest of the application."
      },
      {
        "id": "logieagle-d3-5",
        "station": "Logieagle floor · desk 21",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d3-6",
        "station": "Logieagle floor · desk 22",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d3-7",
        "station": "Logieagle floor · desk 23",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      },
      {
        "id": "logieagle-d3-8",
        "station": "Logieagle floor · desk 24",
        "name": "Untitled workstation",
        "company": "",
        "role": "",
        "duration": "",
        "screen": "code",
        "tech": [],
        "description": "Write what you worked on at this desk.",
        "responsibilities": [],
        "features": [],
        "apis": [],
        "challenge": "",
        "solution": "",
        "impact": ""
      }
    ],

  /* ---------- SIDE PROJECT — the laptop in the lounge */
  sideProject: {
    id: "side",
    name: "India Vehicle Comparison Platform",
    company: "Personal project · in progress",
    role: "Solo — product, frontend, backend",
    duration: "2026 –",
    tech: ["Next.js 14", "Node.js + Express", "PostgreSQL", "Tailwind CSS"],
    description:
      "A car comparison site built around one honest question: what mileage does this car actually give, versus the ARAI figure on the brochure? India-first, starting with Maruti, Hyundai, Tata, Honda, Toyota and Mahindra.",
    features: [
      "ARAI claim vs real-world user-reported mileage, side by side",
      "Efficiency split by city, highway and speed band",
      "Engine specs written in plain language",
      "3-year total cost of ownership",
      "\"Looks vs reality\" score and a middle-class buyer verdict"
    ],
    responsibilities: [
      "Own PostgreSQL database for both spec data and user-submitted logs — no dependency on a third-party API staying alive",
      "Data sourced from FuelEconomy.gov, CarQuery, NHTSA, VAHAN and V3Cars",
      "Phase 1 deliberately scoped: cars only, no login, no payments, no app"
    ],
    impact: "Planned monetisation: dealership leads, featured listings and premium reports."
  },

  /* ---------- NPCs -> collaboration stories.
     These are stand-in colleagues, not real named individuals. */
  employees: [
    {
      id: "npc01", name: "Rohit Sharma", designation: "Senior Frontend Developer", department: "Engineering",
      shirt: 0x4A6FA5, seatKey: "ws02",
      projects: ["HR Service Center", "Analytics Dashboard", "Chrome Extension Toolkit"],
      duration: "About 18 months, same pod",
      mine: ["Feature ownership on HRSC modules", "Reusable component library work", "Code review on shared UI"],
      theirs: ["Architecture decisions", "Review standards", "Mentoring on state management patterns"],
      collab: "We split the frontend by feature area and met at the component library. Most of what I know about keeping a large React codebase from turning into spaghetti came out of his code reviews.",
      tech: ["React", "Redux Toolkit", "TypeScript", "SCSS"]
    },
    {
      id: "npc02", name: "Ankit Verma", designation: "Backend Developer", department: "Engineering",
      shirt: 0x3F7D6B, seatKey: "ws01",
      projects: ["HR Service Center", "Project Management System", "Analytics Dashboard"],
      duration: "Roughly 2 years across two products",
      mine: ["Frontend development", "API integration", "Defining the response shapes the UI actually needed"],
      theirs: ["Spring Boot services", "Database design", "Auth and role model"],
      collab: "The closest working relationship on this list. We agreed contracts before either side built anything, argued about pagination more than once, and I picked up enough Spring Boot to fix small endpoints myself instead of filing a ticket.",
      tech: ["Java Spring Boot", "REST", "JWT", "PostgreSQL"]
    },
    {
      id: "npc03", name: "Priya Nair", designation: "UI/UX Designer", department: "Design",
      shirt: 0x8A5CA8, seatKey: "ws03",
      projects: ["Analytics Dashboard", "Task Management Mobile App", "Shopify Storefront"],
      duration: "About 14 months",
      mine: ["Turning Figma into components", "Flagging states the design didn't cover", "Responsive behaviour"],
      theirs: ["Design system", "Interaction design", "Usability calls with clients"],
      collab: "I'd build the happy path, then come back with the list she hadn't seen yet — empty, loading, error, 400-characters-in-a-40-character-field. Those conversations improved both the design system and my eye for detail.",
      tech: ["Figma", "Design tokens", "Responsive layout"]
    },
    {
      id: "npc04", name: "Sneha Patel", designation: "QA Engineer", department: "Quality Assurance",
      shirt: 0xC2703C, seatKey: "board",
      projects: ["HR Service Center", "Project Management System", "Task Management Mobile App"],
      duration: "Across most of both roles",
      mine: ["Fixing what she found", "Reproducing on real devices", "Adding guard rails so a bug class stopped recurring"],
      theirs: ["Test plans", "Regression suites", "Release sign-off"],
      collab: "She tested the way real users behave — double-clicking submit, going back mid-flow, losing network halfway. A lot of my defensive UI habits are just her bug reports, internalised.",
      tech: ["Manual + regression testing", "Android device testing", "Bug tracking"]
    },
    {
      id: "npc05", name: "Manav Desai", designation: "Project Manager", department: "Delivery",
      shirt: 0x5A6270, seatKey: "meeting",
      projects: ["HR Service Center", "Project Management System", "Shopify Storefront"],
      duration: "Full delivery cycles on three products",
      mine: ["Estimates", "Sprint delivery", "Demoing frontend work to clients"],
      theirs: ["Scope and priority", "Client communication", "Release planning"],
      collab: "Daily standups, sprint planning, retros. He's the reason I learned to give an estimate with the risky part named out loud instead of a single optimistic number.",
      tech: ["Agile / Scrum", "Jira", "Sprint planning"]
    }
  ],

  /* ---------- WHITEBOARD -> skills */
  skills: {
    groups: [
      { label: "Core frontend",   hot: true,  years: "3 yrs 5 mos", items: ["React", "Angular", "Next.js", "React Native", "JavaScript (ES6+)", "TypeScript"] },
      { label: "State & data",    hot: false, years: "3 yrs", items: ["Redux", "Redux Toolkit", "RxJS", "REST API integration", "Reactive Forms"] },
      { label: "Styling",         hot: false, years: "3 yrs 5 mos", items: ["Tailwind CSS", "SCSS", "CSS Grid / Flexbox", "Responsive design"] },
      { label: "Backend I touch", hot: false, years: "2 yrs", items: ["Java Spring Boot", "Node.js + Express", "PostgreSQL", "REST design"] },
      { label: "Platform",        hot: false, years: "2 yrs", items: ["Shopify Liquid", "Chrome Extension APIs", "Firebase", "Git"] }
    ],
    workflow: [
     
    ],
    architecture:""
     
  },

  /* ---------- MEETING ROOM -> experience & teamwork */
  experience: {
    roles: [
      { when: "Mar 2024 – Nov 2025", what: "Frontend Developer", who: "Logieagle Private Limited",
        points: ["HRSC and PMS enterprise modules", "React Native task app", "Analytics dashboard", "Chrome Extension", "RBAC across products"] },
      { when: "May 2022 – Mar 2024", what: "Frontend Developer", who: "Evision IT Solution Pvt. Ltd.",
        points: ["Angular project management system", "Shopify theme development", "Reactive Forms and RxJS-heavy modules", "First exposure to Spring Boot APIs"] }
    ],
    teamwork: [
      "Agile / Scrum: daily standups, sprint planning, retrospectives",
      "Estimation and sprint commitments with a PM",
      "Demoing frontend work directly to clients",
      "Cross-team API contract discussions before build starts",
      "Code review, both directions"
    ],
    clients: "Enterprise HR and delivery teams, plus e-commerce merchants on the Shopify side."
  },

  /* ---------- BOOKSHELF -> education */
  education: {
    degree: "B.E. Computer Engineering",
    school: "LDRP Institute of Technology and Research",
    year: "2022",
    score: "8.0 CGPA",
    extra: [
      "Graduated 2022, working full time from May of the same year",
      "Kept learning on the job: Angular first, React after, React Native and Next.js since",
      "Currently building a full-stack side project to keep the backend muscles honest"
    ]
  },

  /* ---------- COFFEE MACHINE -> easter egg */
  coffee: [
    "Cup 1. Standard operating fuel.",
    "Cup 2. The bug is reproducible now.",
    "Cup 3. You've started refactoring something that worked fine.",
    "Cup 4. Bold. Console.log-driven development begins.",
    "Cup 5. It works. Nobody knows why. Ship it.",
    "Cup 6. Please go home. The office is closing."
  ]
};

/* ==========================================================================
   1b · DOORS  —  one door per chapter of the career.
   Tier is earned by what's behind it, not decoration.
   ========================================================================== */
const DOORS = [
  {
    id: 'evision2', tier: 'silver', tierLabel: 'Silver',
    company: 'Evision IT Solution 207', marker: 'Evision 207',
    role: 'Frontend Developer',
    when: 'Set this in the editor', span: '',
    headline: 'The floor Evision moved into',
    blurb: 'Same team, same job — Evision took a new office and we moved in. Dates and the rest of this copy are still placeholders; open the content editor to set them.',
    stack: ['Angular', 'TypeScript', 'RxJS', 'Reactive Forms', 'Shopify Liquid', 'Java Spring Boot'],
    learned: [
      'Placeholder — replace in the content editor'
    ]
  },
  {
    id: 'evision', tier: 'silver', tierLabel: 'Silver',
    company: 'Evision IT Solution 203 & 204', marker: 'Evision 203 204',
    role: 'Frontend Developer',
    when: 'May 2022 – Mar 2024', span: '1 yr 11 mos',
    headline: 'Where I learned to ship',
    blurb: 'Straight out of LDRP into a delivery team. Angular, Reactive Forms, RxJS, and a Shopify theme practice on the side. This is the floor where I stopped writing code that only worked on my machine.',
    stack: ['Angular', 'TypeScript', 'RxJS', 'Reactive Forms', 'Shopify Liquid', 'Java Spring Boot'],
    learned: [
      'Lazy-loaded feature modules, and why the bundle size is somebody\'s first impression',
      'Centralised HTTP error handling instead of a try/catch in every component',
      'Reading a Spring Boot endpoint before complaining about its payload',
      'Talking to a client without a PM translating for me'
    ]
  },
  {
    id: 'logieagle', tier: 'gold', tierLabel: 'Gold',
    company: 'Logieagle Private Limited',
    role: 'Frontend Developer',
    when: 'Mar 2024 – Nov 2025', span: '1 yr 9 mos',
    headline: 'Where the work got serious',
    blurb: 'Enterprise HR and project systems with real permission models, a React Native app, an analytics dashboard and a Chrome Extension. Four products, one frontend, three teammates I still think about when I write code.',
    stack: ['React', 'Redux Toolkit', 'React Native', 'RBAC', 'Firebase', 'Chrome Extension APIs'],
    learned: [
      'Role-based access control belongs in one map, never scattered across components',
      'Performance work is measured on the cheapest device anyone actually owns',
      'A component library is a negotiation with a designer, not a folder',
      'Manifest V3 will delete your architecture and not apologise'
    ]
  }
/* ===== PLATINUM + DIAMOND — parked for now =================================
   Uncomment this block (and the matching LAYOUTS + nav buttons below) to bring
   both doors back. Door positions in the lobby recalculate automatically.
  {
    id: 'independent', tier: 'platinum', tierLabel: 'Platinum',
    company: 'Independent',
    role: 'Building my own things',
    when: 'Nov 2025 – present', span: 'ongoing',
    headline: 'Where nobody hands me the spec',
    blurb: 'A full-stack side project, freelance work, and the uncomfortable discovery that scoping your own product is harder than building it. Next.js, my own Postgres, my own bad decisions.',
    stack: ['Next.js 14', 'Node.js', 'Express', 'PostgreSQL', 'Tailwind CSS'],
    learned: [
      'Owning the database beats depending on somebody else\'s API staying alive',
      'Phase 1 means cutting the features you\'re most excited about',
      'A product needs a verdict, not just data',
      'Backend skills stop being theoretical the moment nobody else has them'
    ]
  },
  {
    id: 'vacant', tier: 'diamond', tierLabel: 'Diamond',
    company: 'Vacant',
    role: 'Reserved for the next team',
    when: 'Available now', span: 'open',
    headline: 'The one you can fill',
    blurb: 'Empty desk, working monitor, nothing on the walls yet. This is the room where whatever I build next goes — and it stays empty until somebody hires me to furnish it.',
    stack: ['React', 'Next.js', 'TypeScript', 'React Native', 'Node.js'],
    learned: [
      'Frontend roles where the UI is the product, not a wrapper',
      'Teams that write down API contracts before building either side',
      'Somewhere I can keep one foot in the backend',
      'Remote, hybrid or Ahmedabad / Gandhinagar'
    ]
  }
   ========================================================================= */
];

/* What I'm looking for — shown on the empty desk behind the Diamond door */
const VACANCY = {
  title: 'The empty desk',
  intro: 'This desk is set up and waiting. Here\'s what would fill it.',
  looking: [
    'Frontend Developer — React, Next.js or Angular, product-owned UI',
    'Teams that treat state, permissions and error handling as design work',
    'Room to touch the backend when the payload is the problem',
    'Ahmedabad / Gandhinagar, remote, or hybrid'
  ],
  bring: [
    '3 yrs 5 mos of production frontend across two product companies',
    'Enterprise RBAC, dashboards, mobile and Chrome Extension experience',
    'Java Spring Boot and Node.js — I can meet the API halfway',
    'A side project I run end to end, database included'
  ]
};
